### ISSUE TITLE
Missing guidance about new repositories

### ISSUE THREAD

**Issue by filipkral** [Esri/contributing#1]
Hi. These guidelines describe how to contribute to existing repositories (by forking them and sending pull requests), but what if I want to make a new repository and make it available through esri.github page?I'd like to share some of my arcpy helper/wrapper functions and esri.github seems the best place to put it. Can you please update the guidelines to explain what should I do?
Many thanks, Filip.

**Comment by ngoldman** [comment]
@filipkral here are some general guidelines that may be helpful: https://gist.github.com/ngoldman/88ab15a3eeadcb06103b

Maybe those can be formalized into a more concrete process for making internal projects open source.

**Comment by jgravois** [comment]
@filipkral in general we only host projects that are owned/maintained by Esri staff within our GitHub organization.  

that being said, we are **always** happy to hear when people are open sourcing their own work and have several outlets/mechanisms for you to get the word out to our community ([geonet](https://geonet.esri.com/message/447151#447151), [arcgis.com](http://www.arcgis.com/home/item.html?id=5d4995ccdb99429185dfd8d8fb2a513e) etc.)

let me know if i can provide any additional assistance!
