### ISSUE TITLE
Error found

### ISSUE THREAD

**Issue by deerob** [Esri/contributing#12]
Class "MapOptionsSample" has a few errors, first:  class name extends controlPanel and second  on line 229,  "OptionsWindow". both cannot be revolved to a type.

**Comment by jgravois** [comment]
what project are you referring to?  can you provide a link?

**Comment by deerob** [comment]
Hi
Sorry the wrong code pasted the Error i found is: Could not find or load
main class SetInitialMapLocation
the link is

https://github.com/Esri/arcgis-runtime-samples-java/blob/master/src/main/java/com/esri/sampleviewer/samples/map/SetInitialMapLocation.java

**Comment by jgravois** [comment]
awesome.  please log your [issue](https://github.com/Esri/arcgis-runtime-samples-java/issues) in that repository so that team that maintains the code can give you a hand!

**Comment by deerob** [comment]
I have done
thank you
