### ISSUE TITLE
Writing to Feature Services

### ISSUE THREAD

**Issue by esridoyle** [Esri/contributing#2]
Will a future version (or does the current version) of Koop support writing to repositories vi the Feature Service endpoints exposed by Koop?

**Comment by jgravois** [comment]
> Will a future version (or does the current version) of Koop support writing to repositories

the short answer is *no*.

check out my reply [here](https://github.com/koopjs/koop/issues/263#issuecomment-143935974) for more information about this topic and feel free to post a new issue in our repository where we work on [koop](https://github.com/koopjs/koop) if you have more questions.
