### ISSUE TITLE
Explicit name "geoportal" in criteria.jsp

### ISSUE THREAD

**Issue by gcampanile** [Esri/contributing#4]
It seems ther's an explicit reference to the webapp name in file \catalog\search\criteria.jsp:

Line 1499:             <td valign="top"><img id="djtCntDistributedSearchesImg" alt="" src="/geoportal/catalog/images/section_closed.gif"/></td>

**Comment by jgravois** [comment]
not sure what you're talking about.  if you can provide more information, i'd be happy to try and help.
